### ISSUE TITLE
Multiple private folder support

### ISSUE THREAD

**Issue by OllyFN** [OllyFN/public-sync#4]
Pretty self explanatory, the code detects if the privateDir configuration option is an array, and if so it does the same operation on all of the directories inside the array, if its in interactive mode, it asks what to do once and then executes the same action on all of them unless the "allDifferent" configuration option is set to true which if so it asks what to do multiple times.

This sounds a bit complicated but I would imagine its as simple as a single for loop and a few configuration tweaks.

**Comment by LyubomirT** [comment]
I think I might give this issue a try. Could you please assign me?

**Comment by LyubomirT** [comment]
@OllyFN Just to make sure. Do you want `allDifferent` only accessible in interactive mode, or should there be a way of using `allDifferent` for `auto`? For example, an array of actions?

**Comment by OllyFN** [comment]
@LyubomirT allDifferent wouldn't affect the auto mode as that mode requires no user input so it would execute the same action for all the all the privateDirs regardless of the allDifferent setting but if you have any ideas I'm open to hearing them

**Comment by LyubomirT** [comment]
> @LyubomirT allDifferent wouldn't affect the auto mode as that mode requires no user input so it would execute the same action for all the privateDirs regardless of the allDifferent setting but if you have any ideas I'm open to hearing them

I'm thinking about implementing something like:

```js
const defaultConfig = {
  debug: {
    showCopied: false,
    showNotCopied: false,
  },
  publicDir: "dir",
  privateDir: [{"dir1": stuff}, {"dir2": stuff}]
  excludeDirs: excludeDirs,
  overrideExceptions: [],
  addExcludes: [],
  interactive: false,
  override: true,
  allDifferent: true,
};
```

Means that normal actions will only work for single-directory / `allDifferent: false` while the array type will include parameters for directories. Might not be the most convenient way to do that, though...

**Comment by OllyFN** [comment]
@LyubomirT That sounds like a great idea, how about having 3 different ways to initialize privateDir, string which points to a single directory, array of strings which points to multiple directories with all executing the same action and array of objects with the key being the directory and the value being some privateDir actions array or config, unsure if you want to do all the work yourself as I'm happy to help you with this.

**Comment by LyubomirT** [comment]
> @LyubomirT That sounds like a great idea, how about having 3 different ways to initialize privateDir, string which points to a single directory, array of strings which points to multiple directories with all executing the same action and array of objects with the key being the directory and the value being some privateDir actions array or config, unsure if you want to do all the work yourself as I'm happy to help you with this.

Sounds good! I'll take note of that when implementing the update. And don't worry about me doing all the work myself, I'm actually very happy to contribute to the project, and as it seems appealing to me it would be even somewhat fun for me to work on this, rather than difficult.

**Comment by LyubomirT** [comment]
@OllyFN Currently implementing a solution for the issue. I found out that if I use the method of automatically determining the private dir execution type, `allDifferent` will have to only be used for `interactive` as it will be completely useless for `auto`. Does that sound alright for you?

**Comment by OllyFN** [comment]
@LyubomirT Yup, that sounds about right

**Comment by LyubomirT** [comment]
> @LyubomirT Yup, that sounds about right

Roger that, thanks for the info.

**Comment by LyubomirT** [comment]
@OllyFN The base algorithm is now done for both Auto and Interactive. Interactive is a bit broken at the moment now (I have some useless iterations present), I'll create the pull request when I return from this consultation with a doctor and finish some documents. Might take a while, though.

**Comment by OllyFN** [comment]
@LyubomirT That sounds great, take your time, I appreciate your work & interest in the project a lot

**Comment by LyubomirT** [comment]
@OllyFN Sorry for the delay, I couldn't continue working on the update due to having to travel to a different city. 🙏

I'll let you know when I'm done.

**Comment by LyubomirT** [comment]
# Update

Stuck with some sort of infinite loop, trying to patch stuff up.

**Comment by LyubomirT** [comment]
> # Update
> Stuck with some sort of infinite loop, trying to patch stuff up.

# Update

Almost done with the interactive mode, and finished with auto completely—just final touches remaining.

**Comment by LyubomirT** [comment]
@OllyFN Done! Please take a look at #7 and let me know if you would like to change something.
